library/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
	path('', views.HomeView.as_view(), name='home_page'),
	path('book/<pk>', views.BookView.as_view(), name='book_inf'),
	path('add/', views.AddBook.as_view(), name='add_book'),
	path('registration/', views.Registration.as_view(), name='registration'),
	path('login/', views.Login.as_view(), name='login'),
	path('logout/', views.Logout.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minilib/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
]

library/models/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    patronymic = models.CharField(verbose_name='Отчество', 
                               max_length=128, 
                               blank=True, 
                               null=True)
    phone_number = models.CharField(verbose_name='Номер телефона', 
                                max_length=128,
                                blank=True,
                                null=True)
    
    class Meta:
        db_table = 'users'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
 
class Book(models.Model):
    author = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        verbose_name='Автор')
    name = models.CharField('Название книги', max_length=255)
    photo = models.ImageField('Фото', upload_to='book/')
    annotation = models.TextField('Аннотация')
    publication_year = models.PositiveBigIntegerField('Год публикации')
    created_at = models.DateTimeField(
        'created_at', 
        auto_now_add=True, 
        blank=True)
    
    class Meta:
        db_table = 'books'
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
        ordering = ['-created_at']
    
    def __str__(self) -> str:
        return self.name

library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Book, User

class AddNewBookForm(forms.ModelForm):
	name = forms.CharField(
		label='', 
		widget=forms.widgets.Input({ 'placeholder': 'Название книги' }))
	annotation = forms.CharField(
		label='', 
		widget=forms.widgets.Textarea({ 'placeholder': 'Аннотация' }))
	publication_year = forms.IntegerField(
		label='', 
		widget=forms.widgets.Input({ 'placeholder': 'Год публикации' }))
	photo = forms.ImageField(label='')

	class Meta:
		model = Book
		fields = ['name', 'photo', 'annotation', 'publication_year']

class RegistrationForm(UserCreationForm):
	username: forms.Field = forms.CharField(
		label="Имя пользователя",
		help_text = ''
	)
	password1: forms.Field = forms.CharField(
		label="Пароль",
		widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
		help_text = ''
	)
	password2: forms.Field = forms.CharField(
		label="Подтверждение пароля",
		widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
		help_text = ''
	)

	class Meta:
		model = User
		fields = [	'username', 
					'first_name', 
					'last_name', 
					'patronymic', 
					'phone_number']

library/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AddNewBookForm, RegistrationForm
from .models import Book
import typing as tp


class HomeView(ListView):
    model = Book
    template_name: str = 'library/home.html'

class BookView(DetailView):
    model = Book
    template_name: str = 'library/book.html'

class AddBook(LoginRequiredMixin, CreateView):
    form_class = AddNewBookForm
    template_name: str = 'library/add_new_book.html'
    success_url: tp.Optional[str] = '/'
    login_url = '/login/'

    def post(self, request: HttpRequest, *args: tp.Any, **kwargs: tp.Any) -> HttpResponse:
        form = self.get_form()
        if form.is_valid():
            return super().post(request, *args, **kwargs)
        response = JsonResponse({"error": "Проверьте введенные данные!"})
        response.status_code = 403
        return response

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(AddBook, self).form_valid(form)

class Registration(CreateView):
    template_name: str = 'library/registration.html'
    form_class = RegistrationForm
    success_url: tp.Optional[str] = '/'

    def post(self, request: HttpRequest, *args: tp.Any, **kwargs: tp.Any) -> HttpResponse:
        form = self.get_form()
        if form.is_valid():
            return super().post(request, *args, **kwargs)
        response = JsonResponse({
            "error": "Не получилось зарегистрировать пользователя! Проверьте введенные данные!"
            })
        response.status_code = 403
        return response

class Login(LoginView):
    template_name: str = 'library/login.html'

    def post(self, request: HttpRequest, *args: tp.Any, **kwargs: tp.Any) -> HttpResponse:
        form = self.get_form()
        if form.is_valid():
            return super().post(request, *args, **kwargs)
        response = JsonResponse({"error": "Проверьте введенные данные!"})
        response.status_code = 403
        return response

class Logout(LogoutView):
    next_page: tp.Optional[str] = '/'

library/templates/library/add_new_book.html
{% extends 'library/base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<main class="flex-shrink-0">
	<div class="container">
		<form action="" method="POST" enctype="multipart/form-data" id="add_book">
			<div class="alert alert-danger d-none" role="alert"></div>
			{% csrf_token %}
			{% bootstrap_form form %}
			{% bootstrap_button "Добавить" button_type="submit" button_class="btn-primary" id="button" %}
		</form>
	</div>
</main>
{% endblock content %}

{% block scripts %}
	<script type="text/javascript">
		$(document).ready(function () {
			$('#add_book').on('submit', function(event) {
				event.preventDefault();
				if (validate_form()) {
					return false
				}

				var $form = $(this);
				var formData = new FormData($('#add_book')[0]);
				$.ajax({
					type: $form.attr('method'),
					url: $form.attr('action'),
					data: formData,
					cache:false,
					contentType: false,
            		processData: false,
					success: function(response) {
						window.location.href = '{% url 'home_page' %}'
					},
					error: function(response) {
						$('.alert-danger').text(response.responseJSON.error).removeClass('d-none')
					}
				});
			});
	
			function validate_form() {
					$(".invalid_feedback").remove();
	
					// Валидация названия книги
					var book_name = $('#id_name')
					console.log(book_name)
					var flag_bn = false;
					if (book_name.val().length > 128) {
						flag_bn = true;
						book_name.after('<div class="invalid_feedback">Название книги не должно превышать 128 символов!</div>');
						$(".invalid_feedback").css({top: book_name.position().top + book_name.outerHeight() + 2});
					}
					$("#id_name").toggleClass('error_class', flag_bn);

					return (flag_bn)
				}
		})		
	</script> 
{% endblock scripts %}

library/templates/library/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ru" class="h-100">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'library/style.css' %}">
        <title>Мини библиотека!</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
		    {% bootstrap_css %}
		    {% bootstrap_javascript %}
    <link rel="canonical" href="https://getbootstrap.su/docs/5.0/examples/sticky-footer/">
    </head>
    <body class="d-flex flex-column h-100">
		{% include 'library/nav.html' %}
    {% block content %}
    {% endblock content %}
		{% include 'library/footer.html' %}
    {% block scripts %}
    {% endblock scripts %}
    </body>
</html>

library/templates/library/book.html
{% extends 'library/base.html' %}

{% block content %}
<main class="flex-shrink-0">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<img src="{{ object.photo.url }}" id="book_img" />
			</div>
			<div class="col-md-8">
				<h1>{{ object.name }}</h1>
				<p>Автор: {{ object.author }}</p>
				<p>Год издания: {{ object.publication_year }}</p>				
				<p>ID книги: {{ object.id }}</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<b>Аннотация:</b>
				<p>{{ object.annotation }}</p>
			</div>
		</div>
	</div>
</main>
{% endblock content %}

library/templates/library/footer.html
{% load library_tags %}

<footer class="footer mt-auto py-3 bg-light" id="footer">
	<div class="container h-100">
	  <span class="text-muted">{% get_time %}</span>
	</div>
</footer>

library/templates/library/home.html
{% extends 'library/base.html' %}

{% block content %}
	<main class="flex-shrink-0">
	<div class="container">
		<div class="row row-cols-1 row-cols-md-4 g-3">
			{% for book in object_list %}
			<a href="{% url 'book_inf' book.id %}" class="card-link">
				<div class="col">
					<div class="card h-100">
						<img src="{{ book.photo.url }}" class="card-img-top" id="img_card" alt="{{ book.name }}">
						<div class="card-body">
							<h5 class="card-title" id="book_link">{{ book.name }}</h5>
							<p class="card-text">{{ book.author }}</p>
						</div>
					</div>
				</div>
			</a>
			{% endfor %}
		</div>
	</div>
</main>
{% endblock content %}

library/templates/library/login.html
{% extends 'library/base.html' %}
{% load django_bootstrap5 %}

{% block content %}
	<main class="flex-shrink-0" id="login" >
		<div class="container" >
			<div class="row">
				<div class="col-md-offset-3 col-md-12">
					<form action="" method="POST" id="log">
						<div class="alert alert-danger d-none" role="alert"></div>
						{% csrf_token %}
						{% bootstrap_form form %}
						{% bootstrap_button "Войти" button_type="submit" button_class="btn-primary" id="login_button" %}
					</form>
				</div>
			</div>
		</div>
	</main>
{% endblock content %}

{% block scripts %}
<script type="text/javascript">
	$(document).ready(function () {
		$('#log').on('submit', function(event) {
			event.preventDefault();
			if (validate_form()) {
				return false
			}

			var $form = $(this);
			$.ajax({
				type: $form.attr('method'),
				url: $form.attr('action'),
				data: $form.serialize(),
				success: function(response) {
					window.location.href = '{% url 'home_page' %}'
				},
				error: function(response) {
					$('.alert-danger').text(response.responseJSON.error).removeClass('d-none')
				}
			});
		});

		function validate_form() {
				$(".invalid_feedback").remove();

				// Валидация имени пользователя
				var username = $('#id_username')
				var flag_u = false;
				if (username.val().length < 4) {
					flag_u = true;
					username.after('<div class="invalid_feedback">Имя пользователя не может быть короче 4 символов!</div>');
					$(".invalid_feedback").css({top: username.position().top + username.outerHeight() + 2});
				}
				$("#id_username").toggleClass('error_class', flag_u);
				return (flag_u)
			}
	})		
</script> 
{% endblock scripts %}

library/templates/library/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
	<div class="container">
	  <a class="navbar-brand" href="{% url 'home_page' %}">Библиотека</a>
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
		  <li class="nav-item">
			<a class="nav-link active" aria-current="page" href="{% url 'add_book' %}">Добавить книгу</a>
		  </li>
		</ul>
		{% if user.is_authenticated %}
		<span class="navbar-text">
			Вошел как {{ user.username }}
		</span>
		<ul class="navbar-nav justify-content-end">
			<li class="nav-item">
				<a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Выйти</a>
			</li>
		</ul>
		{% else %}
		<ul class="navbar-nav justify-content-end">
			<li class="nav-item">
				<a class="nav-link active" aria-current="page" href="{% url 'login' %}">Войти</a>
			</li>
			<li class="nav-item">
				<a class="nav-link active" aria-current="page" href="{% url 'registration' %}">Регистрация</a>
			</li>
		</ul>
		{% endif %}
	  </div>
	</div>
  </nav>

library/templates/library/registration.html
{% extends 'library/base.html' %}
{% load django_bootstrap5 %}

{% block content %}
	<main class="flex-shrink-0" id="registration" >
		<div class="container">
			<div class="row">
				<div class="col-md-offset-3 col-md-12">
					<form action="" method="POST" id="registr">
						<div class="alert alert-danger d-none" role="alert"></div>
						{% csrf_token %}
						{% bootstrap_form form class="col-md-4" %}
						{% bootstrap_button "Регистрация" button_type="submit" button_class="btn-primary" id="login_button" %}
					</form>
				</div>
			</div>
		</div>
	</main>
{% endblock content %}

{% block scripts %}
<script type="text/javascript">
	$(document).ready(function () {
		$('#registr').on('submit', function(event) {
			event.preventDefault();
			if (validate_form()) {
				return false
			}

			var $form = $(this);
			$.ajax({
				type: $form.attr('method'),
				url: $form.attr('action'),
				data: $form.serialize(),
				success: function(response) {
					window.location.href = '{% url 'home_page' %}'
				},
				error: function(response) {
					$('.alert-danger').text(response.responseJSON.error).removeClass('d-none')
				}
			});
		});

		function validate_form() {
				$(".invalid_feedback").remove();

				// Валидация имени пользователя
				var username = $('#id_username')
				var flag_u = false;
				if (username.val().length < 4) {
					flag_u = true;
					username.after('<div class="invalid_feedback">Имя пользователя должно быть больше 3 символов!</div>');
					$(".invalid_feedback").css({top: username.position().top + username.outerHeight() + 2});

				}
				$("#id_username").toggleClass('error_class', flag_u);

				// Валидация поля Имя
				var first_name = $('#id_first_name');
				var flag_f = false
				if (first_name.val().length === 0) {
					flag_f = true;
					first_name.after('<div class="invalid_feedback">Заполните это поле! Оно важно для нас!</div>');
					$(".invalid_feedback").css({top: first_name.position().top + first_name.outerHeight() + 2});
				}
				$("#id_first_name").toggleClass('error_class', flag_f);

				// Валидация поля Фамилия
				var last_name = $('#id_last_name');
				var flag_l = false;
				if (last_name.val().length === 0) {
					flag_l = true;
					last_name.after('<div class="invalid_feedback">Заполните это поле! Оно важно для нас!</div>');
					$(".invalid_feedback").css({top: last_name.position().top + last_name.outerHeight() + 2});
				}
				$("#id_last_name").toggleClass('error_class', flag_l);

				// Валидация поля Номер телефона
				var phone_number = $('#id_phone_number');
				let regex = /^(\+7|7|8)?[\s\-]?\(?[489][0-9]{2}\)?[\s\-]?[0-9]{3}[\s\-]?[0-9]{2}[\s\-]?[0-9]{2}$/;
				var flag_ph = false;
				if(regex.test(phone_number.val()) === 0) {
					flag_ph = true;
					phone_number.after('<div class="invalid_feedback">Введите корректный номер телефона!</div>');
					$(".invalid_feedback").css({top: last_name.position().top + last_name.outerHeight() + 2});
				}
				$("#id_phone_number").toggleClass('error_class', flag_ph);

				// Валидация паролей
				var passwd1 = $("#id_password1");
				var passwd2 = $("#id_password2");
				
				var v_pass1 = passwd1.val()?false:true;
				var v_pass2 = passwd1.val()?false:true;
				
				if (passwd1.val() != passwd2.val()) {
					v_pass1 = true;
					v_pass2 = true;
					passwd1.after('<div class="invalid_feedback for-pass1">Пароли должны совпадать!</div>');
					$(".for-pass1").css({top: passwd1.position().top + passwd1.outerHeight() + 2});
				} else if (passwd1.val().length < 8) {
					v_pass1 = true;
					v_pass2 = true;
					passwd1.after('<div class="invalid_feedback for-pass1">Длина пароля не может быть меньше 8 символов!</div>');
					$(".for-pass1").css({top: passwd1.position().top + passwd1.outerHeight() + 2});
				} 
				
				$("#id_password1").toggleClass('error_class', v_pass1 );
				$("#id_password2").toggleClass('error_class', v_pass2 );

				return (flag_u || flag_f || flag_l || flag_ph || v_pass1 || v_pass2)
			}
	})		
</script> 
{% endblock scripts %}